apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ include "eso-operator-install.namespace" . }}
  labels:
    {{- include "eso-operator-install.labels" . | nindent 4 }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: {{ .Values.operator.name }}
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.operator.startingCSV }}

