

operator:
  imagePatchCronJob:
    # The service account and associated roles must be created first.
    serviceAccountName: eso-images-patch-sa
    # CronJob will run every 10min
    patchSchedule: '10 * * * *'
  
  operatorConfig:
    deploymentName: "external-secrets-operator"
    image: 
      # Public Container Image 
      #repository: ghcr.io/external-secrets/external-secrets
      # Private Container Image -- Make sure you replace 'eso-build' by your namespace
      repository: "image-registry.openshift-image-registry.svc:5000/eso-build/external-secrets"
      pullPolicy: IfNotPresent
      tag: 'v0.6.1'

  controllerManager:
    startingCSV: external-secrets-operator.v0.6.1
    deploymentName: "external-secrets-operator-controller-manager"
    image:
      # Public Container Image 
      #repository: ghcr.io/external-secrets/external-secrets-helm-operator
      # Private Container Image -- Make sure you replace 'eso-build' by your namespace
      repository: "image-registry.openshift-image-registry.svc:5000/eso-build/external-secrets-helm-operator"
      pullPolicy: IfNotPresent
      tag: 'v0.6.1'