{{- range $appItem := .Values.provider.aws.externalSecret.apps }}
{{ if $appItem.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .localSecretName }}
  namespace: {{ include "eso-secrets-sync.namespace" $ }}
  labels:
    project: {{ $appItem.project }}
    application: {{ $appItem.name }}
    {{- include "eso-secrets-sync.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $appItem.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: eso-secret-store
  data:
  {{- range $keySet := $appItem.keySets }}
  - secretKey: {{ $keySet.templateKey }}
    remoteRef:
      conversionStrategy: None
      decodingStrategy: None
      key: {{ $appItem.remoteSecretBucket }}
      property: {{ $keySet.remoteKey }}
  {{- end }}
  target:
    name: {{ $appItem.localSecretName }}
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
    template:
      type: {{ $appItem.secretType }}
      metadata:
        labels:
          application: {{ $appItem.name }}
          application.group: {{ $appItem.project }}
          {{- include "eso-secrets-sync.labels" $ | nindent 10 }}
      data:
      {{- range $keySet := $appItem.keySets }}
        {{ $keySet.localSecretKey }}: |- 
          {{- if not $keySet.isRemoteValueB64Encoded  }}
          {{ printf "%s .%s %s" "{{" $keySet.templateKey "| trim }}" }}
          {{ else }}
          {{ printf "%s .%s %s" "{{" $keySet.templateKey "| nospace | b64dec }}" }}
          {{- end }}
      {{- end }}
---
{{ end }}
{{- end }}