kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.provider.aws.authSecretName }}
  namespace: {{ include "eso-secrets-sync.namespace" . }}
  labels:
    {{- include "eso-secrets-sync.labels" . | nindent 4 }}
data:
  access-key: "{{ .Values.provider.aws.accessKey | b64enc }}"
  secret-access-key: "{{ .Values.provider.aws.secretAccessKey | b64enc }}"
type: Opaque
