apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
  namespace: {{ include "eso-operator-patch.namespace" . }}
  labels:
    {{- include "eso-operator-patch.labels" . | nindent 4}}
spec:
  certController:
    create: true
    image:
      pullPolicy: {{ .Values.operator.operatorConfig.image.pullPolicy }}
      repository: {{ .Values.operator.operatorConfig.image.repository }}
      tag: {{ .Values.operator.operatorConfig.image.tag }}
    rbac:
      create: true
    requeueInterval: 5m
    serviceAccount:
      create: true
      name: ''
      podLabels:
        {{- include "eso-operator-patch.labels" . | nindent 8 }}
  concurrent: 1
  crds:
    createClusterExternalSecret: false
    createClusterSecretStore: false
  createOperator: true
  image:
    pullPolicy: {{ .Values.operator.operatorConfig.image.pullPolicy }}
    repository: {{ .Values.operator.operatorConfig.image.repository }}
    tag: {{ .Values.operator.operatorConfig.image.tag }}
  installCRDs: false
  leaderElect: false
  # processClusterExternalSecret: true
  # processClusterStore: true
  rbac:
    create: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  scopedRBAC: false
  serviceAccount:
    create: true
    name: ''
  webhook:
    certCheckInterval: 5m
    certDir: /tmp/certs
    create: true
    image:
      pullPolicy: {{ .Values.operator.operatorConfig.image.pullPolicy }}
      repository: {{ .Values.operator.operatorConfig.image.repository }}
      tag: {{ .Values.operator.operatorConfig.image.tag }}
    rbac:
      create: true
    replicaCount: 1
    serviceAccount:
      create: true
      name: ''
